import mongoose from 'mongoose'
import bcrypt from 'bcryptjs'

import * as dotenv from 'dotenv'
import * as path from 'path'
dotenv.config({ path: path.resolve(__dirname, '../../.env') })

const MONGODB_URI = process.env.MONGODB_URI || 'mongodb://localhost:27017/examprep'

async function connectDB() {
  await mongoose.connect(MONGODB_URI)
  console.log('Connected to MongoDB')
}

// ─── Schemas ────────────────────────────────────────────────────────────────

const UserSchema = new mongoose.Schema({
  name: String, email: { type: String, unique: true }, password: String,
  role: { type: String, default: 'student' }, isActive: { type: Boolean, default: true },
  isPaid: { type: Boolean, default: false },
})
const SubjectSchema = new mongoose.Schema({ name: String, code: String, description: String })
const QuestionSchema = new mongoose.Schema({
  question: String, type: { type: String, default: 'MCQ' },
  optionA: String, optionB: String, optionC: String, optionD: String,
  correctAnswer: String, difficulty: { type: String, default: 'MEDIUM' },
  subject: mongoose.Schema.Types.ObjectId, topic: String,
})
const ExamSchema = new mongoose.Schema({
  title: String, subject: mongoose.Schema.Types.ObjectId,
  questions: [mongoose.Schema.Types.ObjectId],
  timeLimit: { type: Number, default: 120 },
  passingMark: { type: Number, default: 50 },
  type: { type: String, default: 'MOCK' },
  isActive: { type: Boolean, default: true },
  description: String,
}, { timestamps: true })

const User = mongoose.models.User || mongoose.model('User', UserSchema)
const Subject = mongoose.models.Subject || mongoose.model('Subject', SubjectSchema)
const Question = mongoose.models.Question || mongoose.model('Question', QuestionSchema)
const Exam = mongoose.models.Exam || mongoose.model('Exam', ExamSchema)

// ─── Question Bank ───────────────────────────────────────────────────────────
// Format: [question, A, B, C, D, correctAnswer, difficulty, topic]
type Q = [string, string, string, string, string, string, string, string]

const MODEL1_QS: Q[] = [
  // Data Structures & Algorithms (1-33)
  ['What is the best way to implement a dynamic array?', 'Use an array and resize it manually', 'Use a linked list and adjust size dynamically', 'Use a hash table to manage resizing', 'Use a stack with fixed size', 'A', 'MEDIUM', 'Data Structures'],
  ['Which data structure implements undo functionality?', 'Queue', 'Stack', 'Linked List', 'Binary Tree', 'B', 'EASY', 'Data Structures'],
  ['Correct way to create a singly linked list in C++?', 'struct Node { int data; Node* next; }', 'class Node with constructor', 'Node { data: int, next: Node }', 'Both A and B', 'D', 'MEDIUM', 'Data Structures'],
  ['Primary advantage of binary heap over BST?', 'Faster searching', 'Faster insertion and deletion', 'Better memory usage', 'Sorting elements in order', 'B', 'MEDIUM', 'Data Structures'],
  ['How to implement a queue using two stacks?', 'Push onto one stack and pop from the other', 'Push into two stacks and reverse before dequeueing', 'Use two stacks in queue-like fashion', 'Use recursion', 'A', 'MEDIUM', 'Data Structures'],
  ['Correct way to implement DFS in a graph?', 'Use a stack to explore nodes', 'Use a queue to explore nodes', 'Use recursion to visit every node', 'Both A and C', 'D', 'MEDIUM', 'Algorithms'],
  ['What happens during hash table collision?', 'One key is removed', 'Both keys stored in linked list at that index', 'Second key is ignored', 'New hash function is created', 'B', 'MEDIUM', 'Data Structures'],
  ['How to implement binary search on sorted array?', 'Compare with middle element and discard one half, repeat', 'Iterate through array comparing each element', 'Create binary tree and search', 'Use recursion to divide array', 'A', 'EASY', 'Algorithms'],
  ['How to implement linked list reversal in C++?', 'Use temp variable and change next pointer direction', 'Recursively reverse by swapping next pointers', 'Allocate new list and copy in reverse', 'Both A and B', 'D', 'MEDIUM', 'Data Structures'],
  ['Most efficient sort for nearly sorted elements?', 'Bubble Sort', 'Quick Sort', 'Insertion Sort', 'Merge Sort', 'C', 'MEDIUM', 'Algorithms'],
  ['Result of binary search on non-sorted array?', 'Finds element at correct index', 'Gives incorrect result or fails to find element', 'Returns middle element', 'Sorts array before searching', 'B', 'EASY', 'Algorithms'],
  ['Quicksort time complexity when pivot is always smallest/largest?', 'O(n log n)', 'O(n^2)', 'Algorithm stops sorting', 'Algorithm uses more memory', 'B', 'MEDIUM', 'Algorithms'],
  ['Space complexity of recursive quicksort?', 'O(1)', 'O(n log n)', 'O(n)', 'O(n^2)', 'C', 'HARD', 'Algorithms'],
  ['Impact of poor hash function on time complexity?', 'All operations still O(1)', 'Operations degrade to O(n)', 'Search remains O(n) but insertions faster', 'No impact on time complexity', 'B', 'MEDIUM', 'Data Structures'],
  ['What happens when BST becomes unbalanced?', 'Becomes linked list, search degrades to O(n)', 'Insertions and deletions improve', 'All operations remain O(log n)', 'Tree automatically balances itself', 'A', 'MEDIUM', 'Data Structures'],
  ['When is BFS more efficient than DFS?', 'When solution is deep in tree', 'When graph is sparse', 'When shortest path required in unweighted graph', 'When searching node in tree with many branches', 'C', 'MEDIUM', 'Algorithms'],
  ['Worst-case O(n^2) in Merge Sort?', 'When input is already sorted', 'When input is randomly shuffled', 'When input is sorted in reverse', 'This does not occur in Merge Sort', 'D', 'HARD', 'Algorithms'],
  ['Main advantage of circular queue over normal queue?', 'Faster access to elements', 'Constant time for enqueue and dequeue', 'Prevents wasted space by using both ends', 'Stores data more efficiently in memory', 'C', 'MEDIUM', 'Data Structures'],
  ['Time complexity of searching in unsorted linked list?', 'O(log n)', 'O(1)', 'O(n)', 'O(n^2)', 'C', 'EASY', 'Data Structures'],
  ['What happens using greedy algorithm without greedy-choice property?', 'Solution would be optimal', 'Algorithm may produce non-optimal solution', 'Problem cannot be solved', 'Algorithm would run infinitely', 'B', 'MEDIUM', 'Algorithms'],
  ['When is heap insert operation O(log n)?', 'When heap is already full', 'When inserting into complete binary tree', 'When element is larger than root in max heap', 'When all elements are identical', 'B', 'MEDIUM', 'Data Structures'],
  ['Floyd-Warshall time complexity?', 'O(n)', 'O(n^2)', 'O(n^3)', 'O(2^n)', 'C', 'HARD', 'Algorithms'],
  ['Impact of DFS with recursion on very large graph?', 'May lead to stack overflow', 'DFS much faster for large graphs', 'Algorithm runs infinitely', 'DFS unaffected by recursion depth', 'A', 'MEDIUM', 'Algorithms'],
  ['Best approach for hash table in large datasets?', 'Always fast search operations', 'Unsure due to hash collisions', 'Prefer linear search', 'Challenging but beneficial for large-scale data', 'D', 'MEDIUM', 'Data Structures'],
  ['Trade-off between time and space complexity in sorting?', 'Prioritize time over space always', 'Choose based on space even if slower', 'Weigh both based on problem constraints', 'Focus solely on time efficiency', 'C', 'MEDIUM', 'Algorithms'],
  ['Trade-off in binary search requiring sorted data?', 'Performance gain worth requirement for sorted data', 'Sorting beforehand is unnecessary overhead', 'Binary search not useful unless array is very large', 'Prefer linear search regardless of order', 'A', 'MEDIUM', 'Algorithms'],
  ['Confidence in quicksort for large random datasets?', 'Confident it performs efficiently in most cases', 'Unsure about worst-case time complexity', 'Prefer merge sort as more predictable', 'Always avoid quicksort due to stack overflow', 'A', 'MEDIUM', 'Algorithms'],
  ['Unbalanced BST and search performance?', 'Confident search still efficient due to small size', 'Unbalanced trees result in inefficient search like linked list', 'Unbalanced trees okay with fewer nodes', 'Unsure but tree can eventually balance itself', 'B', 'MEDIUM', 'Data Structures'],
  ['Attitude toward recursion in DFS?', 'Find recursion intuitive, prefer for simplicity', 'Struggle with recursion due to stack overflow', 'Avoid recursion, prefer iterative DFS', 'Neutral, choose based on specific problem', 'D', 'EASY', 'Algorithms'],
  ['Priority queue for real-time scheduling?', 'Effective and essential for critical task prioritization', 'Skeptical, prefer round-robin', 'Requires too much overhead for simple tasks', 'Unfamiliar with priority queues', 'A', 'MEDIUM', 'Data Structures'],
  ['Risk of stack overflow in recursive algorithms?', 'Risk negligible, use recursion freely', 'Concerned, try to avoid recursion for large datasets', 'Prefer recursion but monitor stack depth', 'Prefer iterative to avoid stack overflow', 'D', 'MEDIUM', 'Algorithms'],
  ['Dynamic programming for optimization problems?', 'Very powerful, accept extra memory cost', 'Prefer greedy algorithms, simpler and memory-efficient', 'Useful only when memory not a concern', 'Avoid due to complexity and memory overhead', 'A', 'HARD', 'Algorithms'],
  ["Graph density impact on Dijkstra's algorithm?", "Performs efficiently regardless of density", "Slower for dense graphs but still usable", "Prefer Bellman-Ford for dense graphs", "Challenging to apply to dense graphs", 'B', 'HARD', 'Algorithms'],
  // Information Science Fundamentals (34-50)
  ['Difference between data and information?', 'Data is raw facts, information is processed data', 'Information is unprocessed, data is analyzed', 'Data and information are interchangeable', 'Data is numerical, information is textual', 'A', 'EASY', 'Information Science'],
  ['Key characteristics of LAN?', 'Covers small geographical area', 'Uses public telecommunication networks', 'Has high-speed data transmission', 'Requires satellite communication', 'A', 'EASY', 'Networking'],
  ['Common cyber threats?', 'Phishing', 'Firewall', 'Ransomware', 'Denial-of-Service attack', 'A', 'EASY', 'Cybersecurity'],
  ['NOT a phase in SDLC?', 'Planning', 'Implementation', 'Hacking', 'Maintenance', 'C', 'EASY', 'Software Engineering'],
  ['Major ethical concerns in information science?', 'Privacy', 'Data Bias', 'Digital Currency', 'Intellectual Property Rights', 'A', 'MEDIUM', 'Ethics'],
  ['Characteristics of good information?', 'Accuracy', 'Relevance', 'Randomness', 'Timeliness', 'A', 'EASY', 'Information Science'],
  ['Advantages of using a DBMS?', 'Reduces data redundancy', 'Provides data security', 'Decreases data consistency', 'Eliminates need for indexing', 'A', 'EASY', 'Database'],
  ['Types of database models?', 'Relational', 'Network', 'Linear', 'Hierarchical', 'A', 'EASY', 'Database'],
  ['Characteristics of WAN?', 'Covers large geographical area', 'Has high-speed data transfer similar to LAN', 'Uses public telecommunication networks', 'Requires local router only', 'A', 'EASY', 'Networking'],
  ['Common network topologies?', 'Star', 'Bus', 'Grid', 'Mesh', 'A', 'EASY', 'Networking'],
  ['Common cybersecurity threats?', 'Phishing', 'Ransomware', 'Cache memory', 'Denial-of-Service attack', 'A', 'EASY', 'Cybersecurity'],
  ['Security mechanisms to protect data?', 'Firewalls', 'Encryption', 'Packet sniffing', 'Multi-factor authentication', 'A', 'EASY', 'Cybersecurity'],
  ['Major programming paradigms?', 'Object-oriented programming', 'Procedural programming', 'Logical networking', 'Static scripting', 'A', 'EASY', 'Programming'],
  ['Key areas of Artificial Intelligence?', 'Machine Learning', 'Natural Language Processing', 'Network Administration', 'Computer Vision', 'A', 'EASY', 'AI'],
  ['Characteristics of AI-based systems?', 'Adaptability', 'Manual processing', 'Self-learning capabilities', 'Fixed rule-based execution', 'A', 'EASY', 'AI'],
  ['Characteristics of Big Data?', 'Volume', 'Velocity', 'Virtualization', 'Verification', 'A', 'EASY', 'Big Data'],
  ['Core technologies of the World Wide Web?', 'HTML', 'CSS', 'Python', 'JavaScript', 'A', 'EASY', 'Web Technology'],
  // Information Science & IR (51-100)
  ['Types of web development?', 'Front-end development', 'Back-end development', 'Network engineering', 'Data administration', 'A', 'EASY', 'Web Technology'],
  ['Important aspects in Human-Computer Interaction?', 'Usability', 'Accessibility', 'Database indexing', 'User experience (UX)', 'A', 'EASY', 'HCI'],
  ['User interface (UI) design principles?', 'Consistency', 'Complexity', 'Feedback', 'Randomness', 'A', 'EASY', 'HCI'],
  ['Common types of cyber attacks?', 'SQL Injection', 'Malware', 'Overclocking', 'Zero-day exploit', 'A', 'EASY', 'Cybersecurity'],
  ['Objectives of digital forensics?', 'Investigating cybercrimes', 'Modifying security logs', 'Collecting and preserving evidence', 'Deleting evidence', 'A', 'MEDIUM', 'Cybersecurity'],
  ['Examples of information retrieval systems?', 'Search engines', 'Digital libraries', 'File compression tools', 'Online databases', 'A', 'EASY', 'Information Retrieval'],
  ['Common techniques used in information retrieval?', 'Indexing', 'Data fragmentation', 'Query processing', 'Packet switching', 'A', 'EASY', 'Information Retrieval'],
  ['Key principles of software engineering?', 'Modularity', 'Maintainability', 'Trial-and-error coding', 'Scalability', 'A', 'EASY', 'Software Engineering'],
  ['Agile software development methodologies?', 'Scrum', 'Waterfall', 'Kanban', 'Linear processing', 'A', 'EASY', 'Software Engineering'],
  ['Types of Information Systems?', 'Management Information Systems (MIS)', 'Decision Support Systems (DSS)', 'Network Latency Systems', 'Enterprise Resource Planning (ERP)', 'A', 'EASY', 'Information Systems'],
  ['Key benefits of using IT in business?', 'Process automation', 'Increased operational efficiency', 'Reduced software compatibility', 'Increased redundancy', 'A', 'EASY', 'Information Systems'],
  ['Types of wireless communication technologies?', 'Wi-Fi', 'Bluetooth', 'Ethernet', '5G', 'A', 'EASY', 'Networking'],
  ['Major drivers of digital transformation in organizations?', 'Cloud computing', 'Increased paperwork', 'Artificial Intelligence', 'Manual workflow processing', 'A', 'MEDIUM', 'Digital Transformation'],
  ['Considered disruptive technologies?', 'Blockchain', 'Virtual Reality (VR)', 'DVD storage', 'Internet of Things (IoT)', 'A', 'MEDIUM', 'Digital Transformation'],
  ['Fundamental data structures?', 'Linked List', 'Stack', 'Bus Topology', 'Hash Table', 'A', 'EASY', 'Data Structures'],
  ['Characteristics of an efficient algorithm?', 'Time efficiency', 'Large memory consumption', 'Space efficiency', 'Complex coding structure', 'A', 'EASY', 'Algorithms'],
  ['Types of software testing?', 'Unit testing', 'Integration testing', 'Cache management', 'Regression testing', 'A', 'EASY', 'Software Engineering'],
  ['Best practices for software quality assurance?', 'Continuous testing', 'Ignoring bug reports', 'Code reviews', 'Delayed user feedback', 'A', 'EASY', 'Software Engineering'],
  ['Key phases of IT project management?', 'Initiation', 'Execution', 'Randomization', 'Closure', 'A', 'EASY', 'Project Management'],
  ['Common project management methodologies?', 'Agile', 'Waterfall', 'Freeform', 'Iterative bypassing', 'A', 'EASY', 'Project Management'],
  ['Essential components of IT infrastructure?', 'Servers', 'Routers', 'Application icons', 'Storage devices', 'A', 'EASY', 'IT Infrastructure'],
  ['What is recall in evaluation of an IR system?', 'Total number of documents retrieved', 'Proportion of relevant documents retrieved out of all available relevant documents', 'Accuracy of query processing', 'Time taken to process query', 'B', 'MEDIUM', 'Information Retrieval'],
  ['Metrics commonly used to evaluate IR system performance?', 'Precision', 'F1 score', 'Word count', 'File storage capacity', 'A', 'MEDIUM', 'Information Retrieval'],
  ['What is Latent Semantic Indexing (LSI)?', 'Technique to find most frequent terms in document collection', 'Method for reducing dimensionality and improving IR accuracy by discovering patterns in word use', 'Technique for sorting search results alphabetically', 'Process to organize data for storage', 'B', 'HARD', 'Information Retrieval'],
  ['What does "vector space model" refer to in IR?', 'Visual representation of search results', 'Method for calculating document similarity based on term frequency and document frequency', 'System for organizing documents in spatial format', 'Technique for querying multimedia data', 'B', 'MEDIUM', 'Information Retrieval'],
  ['Example of a hybrid IR system?', 'System using both term-based indexing and semantic analysis', 'System that stores images and videos only', 'Text-only search engine', 'System limited to Boolean searches', 'A', 'HARD', 'Information Retrieval'],
  ['Commonly used information retrieval models?', 'Boolean model', 'Vector space model', 'Simple machine learning model', 'Binary search model', 'A', 'MEDIUM', 'Information Retrieval'],
  ['How are documents retrieved in Boolean retrieval model?', 'Based on similarity scores', 'By matching exact terms from query with documents containing those terms', 'Based on most common terms in query', 'By estimating document relevance', 'B', 'MEDIUM', 'Information Retrieval'],
  ['Primary advantage of vector space model over Boolean model?', 'Vector space model ranks documents based on relevance rather than exact match', 'Boolean model can handle complex queries', 'Vector space model does not require any indexing', 'Boolean model requires less processing time', 'A', 'MEDIUM', 'Information Retrieval'],
  ['Purpose of web crawling in information retrieval systems?', 'To process and filter data from web pages automatically', 'To analyze quality of images on web', 'To store user data for marketing purposes', 'To display web content', 'A', 'MEDIUM', 'Information Retrieval'],
  ['What is an indexer in context of web search engines?', 'A tool that ranks documents', 'Program that crawls web and creates index of web pages based on keywords', 'Software for storing documents', 'Program for encrypting web data', 'B', 'MEDIUM', 'Information Retrieval'],
  ['Common issues in web search engines?', 'Query ambiguity', 'Inconsistent document ranking', 'Redundant data storage', 'Lack of metadata', 'A', 'MEDIUM', 'Information Retrieval'],
  ['How can AI enhance information retrieval systems?', 'By increasing number of queries processed', 'By using machine learning to improve search accuracy and relevance', 'By storing more documents', 'By improving user interface designs', 'B', 'MEDIUM', 'AI'],
  ['Role of NLP in modern IR systems?', 'It simplifies storage process', 'It allows system to understand and process human language queries more effectively', 'It encrypts documents', 'It accelerates document retrieval', 'B', 'MEDIUM', 'AI'],
  ['Major challenge of current ISR systems?', 'Insufficient hardware for document storage', 'Overabundance of irrelevant results and poor ranking systems', 'Lack of user queries', 'Difficulty in indexing digital content', 'B', 'MEDIUM', 'Information Retrieval'],
  ['Primary purpose of clustering in IR systems?', 'To organize documents into groups based on similarity', 'To reduce size of index', 'To enhance relevance feedback process', 'To store documents in alphabetical order', 'A', 'MEDIUM', 'Information Retrieval'],
  ['"Vocabulary" in context of IR system?', 'List of synonyms used in query', 'List of all terms appearing in document collection', 'Dictionary of document titles', 'List of irrelevant terms', 'B', 'EASY', 'Information Retrieval'],
  ['Best describes inverted index in information retrieval?', 'List of document keywords linked to their corresponding document identifiers', 'Map of document authors', 'Directory of users and their search queries', 'Hierarchical structure for metadata', 'A', 'MEDIUM', 'Information Retrieval'],
  ['In probabilistic model, what predicts document relevance?', 'User preferences', 'Statistical likelihood of relevance based on past queries', 'Document length', 'Document storage location', 'B', 'HARD', 'Information Retrieval'],
  ['Purpose of relevance score in IR system?', 'To determine time taken to retrieve document', "To rank documents based on degree of relevance to user's query", 'To classify documents into categories', 'To assess storage capacity of system', 'B', 'EASY', 'Information Retrieval'],
  ['Retrieval model most commonly used in modern search engines?', 'Vector space model', 'Boolean model', 'Probabilistic model', 'Latent semantic analysis', 'A', 'MEDIUM', 'Information Retrieval'],
  ['Key difference between forward index and inverted index?', 'Forward index lists terms and associated documents, inverted index lists documents and associated terms', 'Forward index used in manual indexing, inverted in automated systems', 'Forward index is slower than inverted index', 'Inverted index stores documents alphabetically', 'A', 'MEDIUM', 'Information Retrieval'],
  ['Technique to improve speed and efficiency of searches in IR?', 'Query expansion', 'Data compression', 'Caching frequently accessed results', 'Reducing document size', 'A', 'MEDIUM', 'Information Retrieval'],
  ['Main function of query expansion in IR systems?', 'To add more terms to user\'s original query to increase likelihood of finding relevant results', 'To reduce number of documents returned in search results', 'To rank documents based on file size', 'To remove unnecessary data from database', 'A', 'MEDIUM', 'Information Retrieval'],
  ['"User intent" in context of IR system?', 'Specific task or goal user has when submitting query', 'Method used to store documents', 'Frequency of term in document', "System's ability to index documents", 'A', 'EASY', 'Information Retrieval'],
  ['Which would likely improve user experience in IR system?', 'Complex query syntax', 'Clear and accurate relevance ranking', 'Large file sizes for documents', 'Unfiltered search results', 'B', 'EASY', 'Information Retrieval'],
  ['Key characteristic of a Single-Page Application (SPA)?', 'Uses multiple web pages to display content', 'Loads all content on single HTML page and dynamically updates content as needed', 'Does not use JavaScript', 'Requires page to reload for every interaction', 'B', 'MEDIUM', 'Web Development'],
  ['Popular CSS framework?', 'React', 'Angular', 'Bootstrap', 'Vue', 'C', 'EASY', 'Web Development'],
  ['Version control system commonly used in web development?', 'SVN', 'Git', 'FTP', 'SSH', 'B', 'EASY', 'Web Development'],
  ['What does "Full Stack Developer" mean?', 'Developer specializing in front-end only', 'Developer working on both front-end and back-end development', 'Developer working only on database management', 'Developer specializing in server-side programming', 'B', 'EASY', 'Web Development'],
]

const MODEL2_QS: Q[] = [
  // Library Science (1-50)
  ['Primary functions of a library?', 'Acquisition', 'Classification', 'Advertising', 'Preservation', 'A', 'EASY', 'Library Science'],
  ['Types of libraries?', 'Public Library', 'Special Library', 'Corporate Library', 'Academic Library', 'A', 'EASY', 'Library Science'],
  ['Components of library collection development?', 'Selection', 'Acquisition', 'Deletion of digital catalogs', 'Physical relocation of books', 'A', 'EASY', 'Library Science'],
  ['Major library classification systems?', 'Dewey Decimal Classification', 'Library of Congress Classification', 'ISBN Cataloging System', 'MARC System', 'A', 'EASY', 'Library Science'],
  ['Key purposes of cataloging in a library?', 'Organization of materials', 'Easy retrieval of resources', 'Selling books to patrons', 'Standardized bibliographic descriptions', 'A', 'EASY', 'Library Science'],
  ['Cataloging standards?', 'MARC', 'AACR2', 'MLA Citation Format', 'Open Data Protocol', 'A', 'EASY', 'Library Science'],
  ['Types of information retrieval systems?', 'Search engines', 'Online Public Access Catalogs (OPAC)', 'Microfilm', 'Digital libraries', 'A', 'EASY', 'Information Retrieval'],
  ['Essential components of reference services?', 'Ready reference services', 'Referral services', 'Catalog printing', 'Literature search', 'A', 'EASY', 'Library Science'],
  ['Characteristics of a good reference source?', 'Accuracy', 'Relevance', 'Expensiveness', 'Limited accessibility', 'A', 'EASY', 'Library Science'],
  ['Major components of a digital library?', 'Digital collections', 'Search interface', 'Printed catalogs', 'Metadata management', 'A', 'EASY', 'Digital Library'],
  ['Common library automation software?', 'Koha', 'Evergreen', 'Adobe Photoshop', 'Windows File Explorer', 'A', 'EASY', 'Library Automation'],
  ['Benefits of library automation?', 'Faster information retrieval', 'Remote access to resources', 'Increased manual data entry', 'Efficient cataloging', 'A', 'EASY', 'Library Automation'],
  ['Key ethical concerns in library science?', 'Privacy of users', 'Censorship of materials', 'Providing incorrect references', 'Copyright compliance', 'A', 'MEDIUM', 'Ethics'],
  ['Fair use principles in copyright law?', 'Purpose and character of use', 'Effect on market value', 'Unlimited duplication', 'Copyright expiration date', 'A', 'MEDIUM', 'Copyright'],
  ['Responsibilities of librarian in intellectual property?', 'Ensuring copyright compliance', 'Educating users on plagiarism', 'Banning all digital resources', 'Selling copyrighted books', 'A', 'MEDIUM', 'Copyright'],
  ['Metadata standards used in libraries?', 'Dublin Core', 'MARC', 'XML', 'TCP/IP', 'A', 'MEDIUM', 'Metadata'],
  ['Major bibliographic databases used in libraries?', 'WorldCat', 'Scopus', 'Internet Archive', 'Wikipedia', 'A', 'EASY', 'Library Science'],
  ['Purpose of bibliographic control?', 'Standardization of records', 'Efficient resource retrieval', 'Random book arrangement', 'Reducing number of books', 'A', 'EASY', 'Library Science'],
  ['Benefits of open access publishing?', 'Free access to research', 'Wider readership', 'High subscription fees', 'Increased research impact', 'A', 'EASY', 'Open Access'],
  ['Examples of open access repositories?', 'PubMed Central', 'arXiv', 'Elsevier', 'ProQuest', 'A', 'EASY', 'Open Access'],
  ['Challenges of open access publishing?', 'Sustainability of funding', 'Quality control', 'Restricted user access', 'Higher paywall fees', 'A', 'MEDIUM', 'Open Access'],
  ['Components of library management?', 'Collection development', 'Budgeting', 'Bookselling', 'Staff training', 'A', 'EASY', 'Library Management'],
  ['Common methods of library user education?', 'Library orientation', 'Information literacy programs', 'Limiting access to OPAC', 'Denying users reference services', 'A', 'EASY', 'Library Science'],
  ['Common challenges in library management?', 'Budget constraints', 'Technology integration', 'Book piracy', 'Staffing issues', 'A', 'MEDIUM', 'Library Management'],
  ['Current trends in library science?', 'Artificial Intelligence in libraries', 'Mobile library services', 'Expansion of print-only resources', 'Digital archiving', 'A', 'MEDIUM', 'Library Science'],
  ['Benefits of AI in libraries?', 'Automated cataloging', 'Personalized recommendations', 'Increased book damage', 'Manual indexing', 'A', 'MEDIUM', 'AI'],
  ['Key challenges in implementing AI in libraries?', 'High implementation costs', 'Data privacy concerns', 'Improved cataloging accuracy', 'Reduced demand for technology', 'A', 'MEDIUM', 'AI'],
  ['Key areas of library advocacy?', 'Government funding for libraries', 'Digital inclusion', 'Reducing library hours', 'Eliminating open access policies', 'A', 'MEDIUM', 'Library Science'],
  ['Common features of Integrated Library Systems?', 'Circulation management', 'Cataloging module', 'Digital image processing', 'User authentication', 'A', 'EASY', 'Library Automation'],
  ['Examples of open-source library automation software?', 'Koha', 'Evergreen', 'Microsoft Access', 'Google Drive', 'A', 'EASY', 'Library Automation'],
  ['Benefits of RFID in libraries?', 'Faster check-in and check-out', 'Improved inventory management', 'Manual barcode scanning', 'Increased book theft', 'A', 'EASY', 'Library Automation'],
  ['Key factors affecting deterioration of library materials?', 'Temperature and humidity', 'Light exposure', 'Proper shelving', 'Biological agents (mold, pests)', 'A', 'MEDIUM', 'Preservation'],
  ['Techniques for preservation of books and documents?', 'Deacidification', 'Digital archiving', 'Manual paper folding', 'Direct exposure to sunlight', 'A', 'MEDIUM', 'Preservation'],
  ['Primary objectives of library conservation?', 'Extend lifespan of materials', 'Preserve historical collections', 'Limit book access', 'Restore damaged documents', 'A', 'MEDIUM', 'Preservation'],
  ['Common knowledge organization systems in libraries?', 'Subject headings', 'Classification schemes', 'ISBN numbering', 'User-generated tags', 'A', 'EASY', 'Knowledge Organization'],
  ['Major controlled vocabularies used in libraries?', 'Library of Congress Subject Headings (LCSH)', 'Medical Subject Headings (MeSH)', 'Oxford Dictionary', 'Art and Architecture Thesaurus (AAT)', 'A', 'MEDIUM', 'Knowledge Organization'],
  ['Indexing techniques used in information retrieval?', 'Boolean indexing', 'Keyword indexing', 'Paper binding', 'Pagination numbering', 'A', 'EASY', 'Information Retrieval'],
  ['Main types of library user services?', 'Reference services', 'Circulation services', 'Public relations', 'Interlibrary loan', 'A', 'EASY', 'Library Science'],
  ['Components of an information literacy program?', 'Evaluating sources', 'Research skills', 'Selling books', 'Deleting outdated catalogs', 'A', 'EASY', 'Information Literacy'],
  ['Strategies to enhance user engagement in libraries?', 'Community programs', 'Digital literacy workshops', 'Reducing library hours', 'Restricting access to online databases', 'A', 'EASY', 'Library Science'],
  ['Characteristics of open-access journals?', 'Free access', 'Peer-reviewed', 'Subscription-based', 'No copyright restrictions', 'A', 'EASY', 'Open Access'],
  ['Well-known institutional repositories?', 'DSpace', 'EPrints', 'YouTube', 'Facebook', 'A', 'EASY', 'Digital Library'],
  ['Major challenges in maintaining digital repositories?', 'Long-term data storage', 'Metadata management', 'Physical book damage', 'Copyright issues', 'A', 'MEDIUM', 'Digital Library'],
  ['Potential applications of AI in libraries?', 'Automated cataloging', 'Chatbot-based reference services', 'Increasing manual indexing', 'Handwritten record keeping', 'A', 'MEDIUM', 'AI'],
  ['Ethical concerns regarding AI use in libraries?', 'User data privacy', 'Bias in recommendation systems', 'Improved access to digital resources', 'Better indexing performance', 'A', 'MEDIUM', 'Ethics'],
  ['AI technologies that improve information retrieval?', 'Natural Language Processing (NLP)', 'Machine Learning (ML)', 'Optical Character Recognition (OCR)', 'Physical book restoration', 'A', 'MEDIUM', 'AI'],
  ['Key trends shaping the future of libraries?', 'Smart libraries', 'Mobile-friendly digital services', 'Increased paper book production', 'AI-driven cataloging', 'A', 'MEDIUM', 'Library Science'],
  ['Challenges faced by modern libraries in digital age?', 'Budget constraints', 'Digital divide', 'Decreased need for technology', 'Increased print collection size', 'A', 'MEDIUM', 'Library Science'],
  ['Ways libraries can adapt to digital transformation?', 'Implementing cloud-based services', 'Enhancing virtual reference services', 'Limiting internet access', 'Increasing print book circulation', 'A', 'MEDIUM', 'Library Science'],
  ['Strategies libraries use to promote lifelong learning?', 'Community engagement programs', 'Digital literacy training', 'Restricted access to reference materials', 'Open educational resources (OER)', 'A', 'EASY', 'Library Science'],
  // Library Cataloging & Classification (51-100)
  ['Main purpose of cataloging in a library?', 'To increase book sales', 'To organize and describe materials for easy retrieval', 'To restrict access to books', 'To remove outdated books', 'B', 'EASY', 'Library Science'],
  ['Classification system widely used in academic libraries?', 'Universal Decimal Classification', 'Library of Congress Classification', 'Colon Classification', 'Sears Classification', 'B', 'EASY', 'Library Science'],
  ['What does OPAC stand for?', 'Online Public Access Catalog', 'Open Public Archive Collection', 'Official Public Access Code', 'Online Publishing and Archival Center', 'A', 'EASY', 'Library Science'],
  ['Which is NOT a type of library?', 'Academic', 'Public', 'Private Enterprise', 'Special', 'C', 'EASY', 'Library Science'],
  ['Primary role of reference services in a library?', 'To lend books', 'To provide research assistance and information access', 'To classify books', 'To issue library cards', 'B', 'EASY', 'Library Science'],
  ['What is Information Science primarily concerned with?', 'The study of information processing', 'The principles of data management', 'The development of software applications', 'The marketing of information products', 'A', 'EASY', 'Information Science'],
  ['Key elements of information science?', 'Information retrieval', 'Knowledge organization', 'Physical book production', 'Human-computer interaction', 'A', 'EASY', 'Information Science'],
  ['Disciplines contributing to Information Science?', 'Computer Science', 'Library Science', 'Mathematics', 'Culinary Arts', 'A', 'EASY', 'Information Science'],
  ['Key functions of an information system?', 'Data processing', 'Storage and retrieval', 'Entertainment media production', 'Communication', 'A', 'EASY', 'Information Systems'],
  ['Examples of information systems?', 'Library databases', 'Enterprise Resource Planning (ERP) systems', 'MP3 music players', 'Social media accounts', 'A', 'EASY', 'Information Systems'],
  ['Characteristics of a well-structured database?', 'Organized data', 'Data integrity', 'High redundancy', 'Easy retrieval', 'A', 'EASY', 'Database'],
  ['Major components of an information retrieval system?', 'Query processing', 'Indexing', 'Data destruction', 'Marketing strategies', 'A', 'EASY', 'Information Retrieval'],
  ['Boolean operators used in search queries?', 'AND', 'OR', 'WITH', 'NOT', 'A', 'EASY', 'Information Retrieval'],
  ['Factors affecting effectiveness of IR system?', 'Relevance of search results', 'User query formulation', 'Network bandwidth', 'Quality of metadata', 'A', 'MEDIUM', 'Information Retrieval'],
  ['Major digital library components?', 'Metadata management', 'Search and retrieval functions', 'Print catalog expansion', 'User interface', 'A', 'EASY', 'Digital Library'],
  ['Classification systems used in knowledge organization?', 'Dewey Decimal Classification (DDC)', 'Library of Congress Classification (LCC)', 'Social media hashtags', 'Barcodes', 'A', 'EASY', 'Knowledge Organization'],
  ['Benefits of digital libraries over traditional libraries?', 'Remote access', 'Multiple-user access', 'Higher maintenance costs', 'Preservation of rare materials', 'A', 'EASY', 'Digital Library'],
  ['Key ethical concerns in Information Science?', 'Data privacy', 'Copyright and intellectual property', 'Monopoly pricing', 'Digital access equity', 'A', 'MEDIUM', 'Ethics'],
  ['Principles of data security?', 'Confidentiality', 'Integrity', 'Unrestricted sharing', 'Open password access', 'A', 'EASY', 'Cybersecurity'],
  ['Best practices for protecting user privacy?', 'Encrypting sensitive data', 'Using strong authentication methods', 'Publicly displaying passwords', 'Restricting access to personal information', 'A', 'EASY', 'Cybersecurity'],
  ['Technologies shaping the future of Information Science?', 'Artificial Intelligence', 'Blockchain', 'Traditional index cards', 'Big Data Analytics', 'A', 'MEDIUM', 'Information Science'],
  ['Applications of AI in Information Science?', 'Automated metadata generation', 'Intelligent search systems', 'Handwritten cataloging', 'Manual data entry', 'A', 'MEDIUM', 'AI'],
  ['Key characteristics of Big Data?', 'Volume', 'Variety', 'Slowness', 'Velocity', 'A', 'EASY', 'Big Data'],
  ['Common storage media for digital information?', 'Cloud storage', 'Optical disks', 'Paper documents', 'Whiteboards', 'A', 'EASY', 'Digital Preservation'],
  ['Major challenges of digital preservation?', 'Data obsolescence', 'File format compatibility', 'Increased physical wear', 'Cybersecurity threats', 'A', 'MEDIUM', 'Digital Preservation'],
  ['Strategies for long-term digital preservation?', 'Regular format migration', 'Redundant storage', 'Single-copy storage', 'Ignoring security updates', 'A', 'MEDIUM', 'Digital Preservation'],
  ['Core principles of Human-Computer Interaction?', 'Usability', 'Accessibility', 'Arbitrary design', 'User experience (UX)', 'A', 'EASY', 'HCI'],
  ['Factors that improve user experience in information systems?', 'Intuitive navigation', 'Clear visual design', 'Complex query input', 'Inconsistent page layout', 'A', 'EASY', 'HCI'],
  ['Factors influencing accessibility in digital systems?', 'Screen reader compatibility', 'Color contrast', 'Complex passwords', 'Keyboard navigation', 'A', 'EASY', 'HCI'],
  ['Principles of open access publishing?', 'Free availability', 'Unrestricted reuse', 'High paywalls', 'Limited citation sharing', 'A', 'EASY', 'Open Access'],
  ['Challenges associated with open access publishing?', 'Sustainability of funding', 'Quality control', 'High print production costs', 'Copyright management', 'A', 'MEDIUM', 'Open Access'],
  ['Widely recognized open-access repositories?', 'PubMed Central', 'arXiv', 'Amazon Books', 'Elsevier', 'A', 'EASY', 'Open Access'],
  ['Common applications of Information Science?', 'Digital libraries', 'Search engines', 'Spacecraft navigation', 'Business intelligence', 'A', 'EASY', 'Information Science'],
  ['Benefits of cloud computing in information storage?', 'Scalability', 'Remote access', 'Fixed storage space', 'Higher risk of loss', 'A', 'EASY', 'Cloud Computing'],
  ['Key considerations in developing an information system?', 'System security', 'User requirements', 'Color of website background', 'Data integrity', 'A', 'MEDIUM', 'Information Systems'],
  ['Main purpose of an Information Retrieval (IR) system?', 'To store documents in physical form', 'To facilitate retrieval of relevant information from large datasets', 'To secure sensitive data', 'To provide entertainment media', 'B', 'EASY', 'Information Retrieval'],
  ['What does an IR system primarily focus on?', 'Data analysis', 'Managing metadata', 'Searching and retrieving information efficiently', 'Creating new documents', 'C', 'EASY', 'Information Retrieval'],
  ['Typical components of an IR system?', 'Query processor', 'User interface', 'Data encryption', 'Optical storage medium', 'A', 'EASY', 'Information Retrieval'],
  ['Common types of storage media in IR systems?', 'Magnetic disks', 'Optical discs', 'Printed books', 'Flash drives', 'A', 'EASY', 'Information Retrieval'],
  ['Purpose of an index in an IR system?', 'To speed up document storage', 'To facilitate faster document retrieval', 'To prevent unauthorized access', 'To backup data', 'B', 'EASY', 'Information Retrieval'],
  ['Difference between primary and secondary storage in ISR?', 'Primary for permanent, secondary for temporary', 'Primary faster and directly accessible, secondary holds data longer-term', 'Secondary for active retrieval, primary for passive backup', 'No difference', 'B', 'MEDIUM', 'Information Retrieval'],
  ['Main purpose of indexing in an IR system?', 'To enhance data encryption', 'To organize and optimize the search process', 'To ensure redundancy in storage', 'To facilitate data entry', 'B', 'EASY', 'Information Retrieval'],
  ['Common indexing techniques used in IR systems?', 'Inverted indexing', 'Contextual indexing', 'Dynamic indexing', 'Structural indexing', 'A', 'MEDIUM', 'Information Retrieval'],
  ['What is term frequency (TF) in information retrieval?', 'Frequency of unique terms in entire collection', 'Number of times a term appears in a document', 'Total number of documents in system', 'Time it takes to retrieve a document', 'B', 'MEDIUM', 'Information Retrieval'],
  ['What does relevance of a document mean in IR?', 'Physical location of document', 'Degree to which document satisfies query requirements', 'Number of times document has been accessed', 'File size of document', 'B', 'EASY', 'Information Retrieval'],
  ['Algorithm commonly used to rank search results?', "Dijkstra's Algorithm", 'PageRank Algorithm', 'Floyd-Warshall Algorithm', 'QuickSort Algorithm', 'B', 'MEDIUM', 'Information Retrieval'],
  ['Purpose of ranking in an IR system?', 'To sort documents randomly', 'To order results based on relevance to query', 'To remove irrelevant documents from storage', 'To store documents in specific order', 'B', 'EASY', 'Information Retrieval'],
  ['What is a query in the context of an IR system?', 'A document stored in the system', 'A user request for information or documents', 'A search result', 'A metadata descriptor', 'B', 'EASY', 'Information Retrieval'],
  ['Boolean operators used for in IR systems?', 'Combining query terms to refine search results', 'Ranking search results', 'Enhancing image processing', 'Limiting search scope', 'A', 'EASY', 'Information Retrieval'],
  ['What is relevance feedback in IR systems?', 'System automatically filters irrelevant documents', 'System ranks results based on user feedback about relevance', 'Users manually classify documents', "System's ability to understand context automatically", 'B', 'MEDIUM', 'Information Retrieval'],
  ['What is precision in evaluation of an IR system?', 'Number of relevant documents retrieved', 'Proportion of retrieved documents that are relevant', 'Total number of documents in system', 'Speed at which documents are retrieved', 'B', 'MEDIUM', 'Information Retrieval'],
]

const MODEL3_QS: Q[] = [
  // Programming & Visual Basic (1-65)
  ['Characteristic of a high-level programming language?', 'It is machine-dependent', 'It uses binary code directly', 'It is human-readable and abstracted from hardware', 'It requires no compilation', 'C', 'EASY', 'Programming'],
  ['What does a compiler do?', 'Runs program line by line', 'Converts high-level code to machine code', 'Optimizes runtime speed', 'Stores variables', 'B', 'EASY', 'Programming'],
  ['Valid variable name in most programming languages?', '123abc', '_myVar', '@variable', 'var#1', 'B', 'EASY', 'Programming'],
  ['Not a primitive data type in most programming languages?', 'int', 'float', 'string', 'object', 'D', 'EASY', 'Programming'],
  ['Correct statement about variables?', 'Variables can store only numbers', 'Variables store data for use during program execution', 'Variables cannot be changed once initialized', 'Variables can only store string data', 'B', 'EASY', 'Programming'],
  ['Default value of a boolean variable in most languages?', '1', '0', 'null', 'false', 'D', 'EASY', 'Programming'],
  ['Control structure used for decision-making?', 'for loop', 'if statement', 'while loop', 'switch statement', 'B', 'EASY', 'Programming'],
  ['What does a "for" loop do?', 'Executes code a specific number of times', 'Repeats code indefinitely', 'Executes code only if condition is true', 'Terminates the program', 'A', 'EASY', 'Programming'],
  ['Purpose of the "break" statement in loops?', 'To stop the program', 'To skip current iteration', 'To exit the loop prematurely', 'To initiate a new loop', 'C', 'EASY', 'Programming'],
  ['Output of Python: x=10, if x>5: print("Greater") else: print("Smaller")?', 'Smaller', 'Greater', 'Error', 'Nothing', 'B', 'EASY', 'Programming'],
  ['Main purpose of functions in programming?', 'To execute the program', 'To store data values', 'To encapsulate reusable blocks of code', 'To define variable names', 'C', 'EASY', 'Programming'],
  ['What does the return statement do in a function?', 'It stops the program', 'It prints output to screen', 'It sends a value back to the caller', 'It calls another function', 'C', 'EASY', 'Programming'],
  ['Output of: def greet(name): return "Hello "+name; print(greet("Alice"))?', 'Alice', 'Hello Alice', 'greet Alice', 'Error', 'B', 'EASY', 'Programming'],
  ['Feature of a recursive function?', 'It calls itself in its own definition', 'It has a fixed number of iterations', 'It runs without any base case', 'It uses a while loop internally', 'A', 'MEDIUM', 'Programming'],
  ['What is an array in programming?', 'A function that stores values', 'A variable that can store multiple values of same type', 'A structure used for user input', 'A way of storing only one value', 'B', 'EASY', 'Programming'],
  ['Which language uses list for ordered collections?', 'C++', 'Java', 'Python', 'Assembly', 'C', 'EASY', 'Programming'],
  ['Output of Python: arr=[1,2,3,4]; arr[2]=10; print(arr)?', '[1, 2, 10, 4]', '[1, 2, 3, 4]', '[10, 2, 3, 4]', 'Error', 'A', 'EASY', 'Programming'],
  ['Primary advantage of array over list?', 'Arrays are dynamic in size', 'Arrays provide better performance for indexing', 'Lists are faster than arrays', 'Arrays can store any data type', 'B', 'MEDIUM', 'Programming'],
  ['Not a key concept of OOP?', 'Encapsulation', 'Inheritance', 'Abstraction', 'Compilation', 'D', 'EASY', 'OOP'],
  ['What does "inheritance" mean in OOP?', 'A class can access methods from another class', 'Objects can only have one method', 'A class cannot have private variables', 'Objects are stored in memory', 'A', 'EASY', 'OOP'],
  ['Example of polymorphism in OOP?', 'A class with multiple constructors', 'A method that behaves differently based on input type', 'A class that cannot be modified', 'An object that cannot access its own properties', 'B', 'MEDIUM', 'OOP'],
  ['What does "self" keyword represent in Python OOP?', 'The current instance of the class', 'A function inside a class', 'A reference to a parent class', 'A reference to a global variable', 'A', 'EASY', 'OOP'],
  ['Purpose of try-except block in programming?', 'To repeat a block of code multiple times', 'To handle exceptions or errors during execution', 'To create a new variable', 'To define a function', 'B', 'EASY', 'Programming'],
  ['Which would likely cause a runtime error?', 'Division by zero', 'Assigning a value to a variable', 'Defining a function', 'Printing output', 'A', 'EASY', 'Programming'],
  ['Purpose of debugging in programming?', 'To optimize program for performance', 'To find and fix errors or bugs in code', 'To enhance code readability', 'To add comments', 'B', 'EASY', 'Programming'],
  ['Time complexity of binary search on sorted array?', 'O(n)', 'O(log n)', 'O(n^2)', 'O(1)', 'B', 'EASY', 'Algorithms'],
  ["What does algorithm's time complexity refer to?", 'Number of lines of code', 'Amount of time algorithm takes as input size grows', 'Memory used by algorithm', 'Number of iterations required', 'B', 'EASY', 'Algorithms'],
  ['Best algorithm for sorting large collection of random data?', 'Bubble Sort', 'Merge Sort', 'Linear Search', 'Insertion Sort', 'B', 'MEDIUM', 'Algorithms'],
  ['Key characteristic of a greedy algorithm?', 'Makes decisions based on global optimal solution', 'Looks ahead at all possible outcomes', 'Makes locally optimal choices hoping for global optimum', 'Uses recursion', 'C', 'MEDIUM', 'Algorithms'],
  ['What best describes multithreading?', 'Running multiple programs in parallel', 'Ability to write in multiple languages', 'Running multiple threads within same program simultaneously', 'A method for optimizing memory usage', 'C', 'MEDIUM', 'Programming'],
  ['Default data type of variable in Visual Basic if no type specified?', 'Integer', 'String', 'Object', 'Boolean', 'C', 'EASY', 'Visual Basic'],
  ['Keyword used to declare a variable in Visual Basic?', 'Dim', 'Var', 'Declare', 'Let', 'A', 'EASY', 'Visual Basic'],
  ['Correct way to declare and initialize variable in Visual Basic?', 'Dim x = 10', 'Dim x As Integer = 10', 'x As Integer = 10', 'Integer x = 10', 'B', 'EASY', 'Visual Basic'],
  ['Value type in Visual Basic?', 'String', 'Object', 'Integer', 'Array', 'C', 'EASY', 'Visual Basic'],
  ['What does "If...Then" statement do in Visual Basic?', 'Repeats code based on condition', 'Executes code based on condition', 'Declares a variable', 'Stops the program', 'B', 'EASY', 'Visual Basic'],
  ['Control structure in Visual Basic for multiple conditions?', 'If...Then', 'Select Case', 'While...End While', 'For...Next', 'B', 'EASY', 'Visual Basic'],
  ['Output: Dim x=5; If x>3 Then Console.WriteLine("Greater") Else Console.WriteLine("Smaller")?', 'Smaller', 'Greater', 'Error', 'Nothing', 'B', 'EASY', 'Visual Basic'],
  ['Loop that repeats code a specified number of times in VB?', 'Do While', 'For...Next', 'While...End While', 'Loop Until', 'B', 'EASY', 'Visual Basic'],
  ['Difference between Function and Sub in Visual Basic?', 'Function returns value, Sub does not', 'Sub returns value, Function does not', 'Functions for debugging, Subs for executing', 'No difference', 'A', 'EASY', 'Visual Basic'],
  ['Correct syntax for defining a Function in Visual Basic?', 'Function MyFunction() As Integer', 'Function MyFunction()', 'Sub MyFunction() As Integer', 'Function MyFunction() As String', 'A', 'EASY', 'Visual Basic'],
  ['Output: Function Sum(a,b) Return a+b; Console.WriteLine(Sum(3,4))?', '34', '7', 'Error', '3', 'B', 'EASY', 'Visual Basic'],
  ['Correct way to call a Function in Visual Basic?', 'FunctionName()', 'Call FunctionName()', 'FunctionName(parameter)', 'Call FunctionName(parameter)', 'C', 'EASY', 'Visual Basic'],
  ['Not a fundamental principle of OOP?', 'Encapsulation', 'Inheritance', 'Polymorphism', 'Compiling', 'D', 'EASY', 'OOP'],
  ['Keyword used to define a class in Visual Basic?', 'Class', 'Object', 'Type', 'Define', 'A', 'EASY', 'Visual Basic'],
  ['What does "Inherits" keyword do in Visual Basic?', 'Defines a property in a class', 'Creates a new instance of a class', 'Specifies that a class derives from another class', 'Calls a method from a class', 'C', 'EASY', 'Visual Basic'],
  ['What is used to encapsulate data and methods in VB class?', 'Interfaces', 'Properties', 'Arrays', 'Loops', 'B', 'MEDIUM', 'Visual Basic'],
  ['True about constructors in Visual Basic?', 'Used to initialize objects when created', 'Used to delete objects', 'Can only take one parameter', 'Cannot be overloaded', 'A', 'EASY', 'Visual Basic'],
  ['How to declare an array in Visual Basic?', 'Dim arr As Integer(5)', 'Dim arr(5) As Integer', 'Dim arr As Integer(5) = {1,2,3,4,5}', 'Dim arr() As Integer = {1,2,3,4,5}', 'D', 'EASY', 'Visual Basic'],
  ['Default value of uninitialized array element in Visual Basic?', '0', 'Null', 'False', 'Empty', 'A', 'EASY', 'Visual Basic'],
  ['Method to add item to a list in Visual Basic?', 'AddItem()', 'List.Add()', 'InsertItem()', 'Append()', 'B', 'EASY', 'Visual Basic'],
  ['Purpose of "Try...Catch" block in Visual Basic?', 'To define a function', 'To handle errors or exceptions during runtime', 'To declare variables', 'To repeat a block of code', 'B', 'EASY', 'Visual Basic'],
  ['Correct syntax for Try...Catch block in Visual Basic?', 'Try {code} Catch {code} End Try', 'Try {code} Catch {error} End Catch', 'Try {code} Catch ex As Exception {code} End Try', 'Try {code} Finally {code}', 'C', 'EASY', 'Visual Basic'],
  ['Function of "Throw" keyword in Visual Basic?', 'Generates an exception intentionally', 'Terminates the program', 'Rethrows the last exception', 'Continues execution of program', 'A', 'EASY', 'Visual Basic'],
  ['Method to read entire contents of text file in Visual Basic?', 'File.ReadAllText()', 'File.ReadLine()', 'File.Read()', 'File.GetContents()', 'A', 'EASY', 'Visual Basic'],
  ['Correctly write data to a file in Visual Basic?', 'File.Write("path","data")', 'FileStream.Write("data")', 'StreamWriter.WriteLine("data")', 'WriteText("data")', 'C', 'EASY', 'Visual Basic'],
  ['True about "With" statement in Visual Basic?', 'Used to initialize arrays', 'Allows multiple operations on object without repeatedly referencing it', 'Used to handle exceptions', 'Defines a new class', 'B', 'EASY', 'Visual Basic'],
  ['What does "Handles" keyword specify in event handler?', 'Indicates method to handle an event', 'Defines the event', 'Assigns property to an event', 'Handles exceptions during event', 'A', 'EASY', 'Visual Basic'],
  ['Purpose of "Imports" keyword in Visual Basic?', 'To declare variables', 'To define a class', 'To include external libraries or namespaces', 'To create new methods', 'C', 'EASY', 'Visual Basic'],
  ['What does "Debugger" tool in Visual Basic do?', 'Compiles the program', 'Helps find and fix bugs in code', 'Optimizes program for better performance', 'Writes code for you', 'B', 'EASY', 'Visual Basic'],
  ['How to step through code during debugging in Visual Basic?', 'Press F5 to run program', 'Press F10 to step through code line by line', 'Press F12 to start debugging', 'Press F6 to skip errors', 'B', 'EASY', 'Visual Basic'],
  ['Used to comment a line of code in Visual Basic?', '//', '#', "'", '/* */', 'C', 'EASY', 'Visual Basic'],
  ['Purpose of "Option Strict" statement in Visual Basic?', 'Limits use of integers', 'Enforces type safety by disallowing implicit type conversions', 'Restricts variable naming', 'Enables debugging', 'B', 'MEDIUM', 'Visual Basic'],
  ['Reference type in Visual Basic?', 'Integer', 'String', 'Boolean', 'Double', 'B', 'EASY', 'Visual Basic'],
  ['Default value of Boolean variable in Visual Basic?', 'True', 'False', 'Null', '0', 'B', 'EASY', 'Visual Basic'],
  ['Output: Dim x=5; Dim y=3; Console.WriteLine(x+y)?', '35', '8', 'Error', '53', 'B', 'EASY', 'Visual Basic'],
  // Web Development (66-100)
  ['What does HTML stand for?', 'HyperText Markup Language', 'HyperText Machine Language', 'HyperTool Markup Language', 'HighText Markup Language', 'A', 'EASY', 'Web Development'],
  ['Tag used to define a hyperlink in HTML?', '<link>', '<a>', '<href>', '<url>', 'B', 'EASY', 'Web Development'],
  ['Correct syntax for inserting an image in HTML?', '<img src="image.jpg" alt="image">', '<image src="image.jpg">', '<img link="image.jpg">', '<image link="image.jpg" alt="image">', 'A', 'EASY', 'Web Development'],
  ['Attribute to specify source of an image in HTML?', 'href', 'src', 'alt', 'link', 'B', 'EASY', 'Web Development'],
  ['HTML tag used to create an ordered list?', '<ul>', '<ol>', '<li>', '<dl>', 'B', 'EASY', 'Web Development'],
  ['Tag used to create a table in HTML?', '<table>', '<tab>', '<table-data>', '<td>', 'A', 'EASY', 'Web Development'],
  ['What does CSS stand for?', 'Cascading Style Sheet', 'Computer Style Sheets', 'Creative Style Sheets', 'Colorful Style Sheets', 'A', 'EASY', 'Web Development'],
  ['Used to change background color of webpage using CSS?', 'background-color', 'color', 'bgcolor', 'background', 'A', 'EASY', 'Web Development'],
  ['Correct syntax for referring to external CSS file?', '<style src="styles.css">', '<link rel="stylesheet" type="text/css" href="styles.css">', '<link rel="stylesheet" href="styles.css">', '<style href="styles.css">', 'B', 'EASY', 'Web Development'],
  ['Property used to change font size in CSS?', 'font-size', 'text-size', 'font', 'text-font', 'A', 'EASY', 'Web Development'],
  ['How to center-align a block element in CSS?', 'text-align: center;', 'align: center;', 'margin: auto;', 'center: true;', 'C', 'EASY', 'Web Development'],
  ['What does display:none property in CSS do?', 'Hides element without removing it', 'Hides element and removes it from document flow', 'Makes element transparent', "Changes element's color", 'B', 'EASY', 'Web Development'],
  ['What does JavaScript allow you to do on a webpage?', 'Add interactivity and dynamic content', 'Structure the content', 'Style the webpage', 'All of the above', 'A', 'EASY', 'Web Development'],
  ['Correct way to define a variable in JavaScript?', 'let x = 10;', 'var x := 10;', 'let x := 10;', 'variable x = 10;', 'A', 'EASY', 'Web Development'],
  ['Output of JavaScript: console.log(2 + "2")?', '22', '4', '"22"', '"4"', 'A', 'EASY', 'Web Development'],
  ['JavaScript event when user clicks on HTML element?', 'onmouseover', 'onchange', 'onclick', 'onload', 'C', 'EASY', 'Web Development'],
  ['Correct syntax for a function in JavaScript?', 'function = myFunction() {}', 'function myFunction() {}', 'function myFunction[] {}', 'function myFunction[]', 'B', 'EASY', 'Web Development'],
  ['Used to get value of input field in JavaScript?', 'getValue()', 'document.getElementById("id").value', 'document.getElementById("id").getValue()', 'value.getElementById("id")', 'B', 'EASY', 'Web Development'],
  ['Purpose of Document Object Model (DOM) in JavaScript?', 'To structure data of webpage', 'To provide structured representation of HTML as tree', 'To style webpage dynamically', 'To allow users to navigate webpage', 'B', 'MEDIUM', 'Web Development'],
  ['JavaScript method used to add new element to DOM?', 'document.createElement()', 'document.addElement()', 'document.newElement()', 'document.insertElement()', 'A', 'EASY', 'Web Development'],
  ['What does innerHTML property do in JavaScript?', 'Changes content of HTML element', 'Sets styles of element', 'Creates new HTML element', 'Returns attributes of element', 'A', 'EASY', 'Web Development'],
  ['JavaScript method used to remove element from DOM?', 'removeElement()', 'removeChild()', 'deleteChild()', 'deleteElement()', 'B', 'EASY', 'Web Development'],
  ['What does PHP stand for?', 'Personal Hypertext Processor', 'PHP: Hypertext Preprocessor', 'Pre-Hypertext Processor', 'Programming Hypertext Preprocessor', 'B', 'EASY', 'Web Development'],
  ['Correct syntax for declaring variable in PHP?', 'var x = 10;', '$x = 10;', 'let x = 10;', 'int x = 10;', 'B', 'EASY', 'Web Development'],
  ['Method used to send data to server in PHP?', 'GET', 'POST', 'FETCH', 'SEND', 'B', 'EASY', 'Web Development'],
  ['PHP function to include external file?', 'include()', 'require()', 'import()', 'insert()', 'A', 'EASY', 'Web Development'],
  ['Correct way to include module in Node.js?', "import module from 'module'", "require('module')", "include 'module'", "module('module')", 'B', 'EASY', 'Web Development'],
  ['What does HTTP stand for?', 'HyperText Transfer Protocol', 'HyperTool Transfer Protocol', 'HyperText Transfer Protocol Secure', 'HyperTransport Transfer Protocol', 'A', 'EASY', 'Web Development'],
  ['Purpose of HTTPS?', 'Provides faster data transfer', 'Encrypts data for secure transmission over internet', 'Formats webpage content', 'Handles user authentication', 'B', 'EASY', 'Web Development'],
  ['Used to fetch data asynchronously in JavaScript?', 'XMLHttpRequest()', 'AJAXRequest()', 'HTTPGetRequest()', 'fetchData()', 'A', 'EASY', 'Web Development'],
  ['What does REST stand for in web services?', 'Real-time Efficient Service Technology', 'Representational State Transfer', 'Rapid Engineered Software Transfer', 'Realtime Server Event Transfer', 'B', 'EASY', 'Web Development'],
  ['Method to prevent Cross-Site Scripting (XSS) attacks?', 'Validating input and encoding output', 'Using a CAPTCHA', 'Enabling cookies', 'Disabling JavaScript', 'A', 'MEDIUM', 'Cybersecurity'],
  ['What does SQL Injection refer to?', 'Inserting data into database securely', "Manipulating webpage's content", 'Maliciously injecting SQL code to access database', 'Encrypting a database', 'C', 'MEDIUM', 'Cybersecurity'],
  ['Primary purpose of responsive web design?', 'To design mobile-friendly websites', 'To make websites load faster', 'To create websites for specific screen sizes', 'To ensure cross-browser compatibility', 'A', 'EASY', 'Web Development'],
  ['Purpose of a favicon?', 'Used for adding advertisements', 'Small icon displayed in browser tab', 'Used to create stylish header', 'Enhances page load speed', 'B', 'EASY', 'Web Development'],
]

const MODEL4_QS: Q[] = [
  // Database & Networking (1-50)
  ['Main function of a Database Management System (DBMS)?', 'To store data in physical storage', 'To allow multiple users to access and manage databases concurrently', 'To handle data manipulation without SQL queries', 'To maintain the operating system', 'B', 'EASY', 'Database'],
  ['What is a schema in a database?', 'The layout or design of a database structure', 'A set of rules that restricts data types', 'A query language used for managing data', 'A list of tables in the database', 'A', 'EASY', 'Database'],
  ['Characteristic of a relational database?', 'Data organized in documents or objects', 'Data stored in tables with rows and columns', 'Data stored in key-value pairs', 'Data represented in hierarchical format', 'B', 'EASY', 'Database'],
  ['SQL command used to modify existing records?', 'UPDATE', 'SELECT', 'INSERT', 'DELETE', 'A', 'EASY', 'Database'],
  ['Constraint ensuring each row has unique identifier?', 'Foreign Key', 'Primary Key', 'Check Constraint', 'Not Null', 'B', 'EASY', 'Database'],
  ['SQL clause used to filter records based on condition?', 'SELECT', 'WHERE', 'FROM', 'GROUP BY', 'B', 'EASY', 'Database'],
  ['What is normalization in databases?', 'Process of duplicating data for redundancy', 'Process of organizing data to reduce redundancy and dependency', 'Process of backing up database regularly', 'Process of compressing data for storage', 'B', 'EASY', 'Database'],
  ['What is a foreign key in a relational database?', 'Unique identifier for each row', 'Key used to link two tables together', 'Key used to validate input data', 'Key that helps sort records', 'B', 'EASY', 'Database'],
  ['Type of relationship in a relational database?', 'One-to-One', 'One-to-None', 'Many-to-One', 'All of the above', 'A', 'EASY', 'Database'],
  ['SQL statement used to remove a table from database?', 'DROP TABLE', 'DELETE TABLE', 'REMOVE TABLE', 'ERASE TABLE', 'A', 'EASY', 'Database'],
  ['Primary purpose of a DBMS?', 'To store data on physical media', 'To manage and organize data efficiently', 'To create a backup of the database', 'To run queries against the data', 'B', 'EASY', 'Database'],
  ['What do rows represent in a relational database table?', 'Data types', 'Records', 'Fields', 'Indexes', 'B', 'EASY', 'Database'],
  ['What is a primary key in a relational database?', 'A key that can have duplicate values', 'A key that uniquely identifies each record', 'A key that references another table', 'A key used to encrypt data', 'B', 'EASY', 'Database'],
  ['SQL command used to retrieve data from database?', 'INSERT', 'DELETE', 'SELECT', 'UPDATE', 'C', 'EASY', 'Database'],
  ['Purpose of a foreign key in relational database?', 'To delete records from table', 'To ensure data consistency', 'To create relationship between two tables', 'To provide unique identifier for records', 'C', 'EASY', 'Database'],
  ['What is normalization in database design?', 'Organizing data to minimize redundancy and dependency', 'Creating indexes to speed up queries', 'Securing data against unauthorized access', 'Converting data into standard format', 'A', 'EASY', 'Database'],
  ['True about ACID properties in database transaction?', 'ACID: Atomicity, Consistency, Isolation, Durability', 'ACID: Application, Consistency, Integration, Data', 'ACID: Accuracy, Consistency, Integration, Data', 'ACID: Automatic, Consistent, Integrity, Data', 'A', 'MEDIUM', 'Database'],
  ['Function of an index in a database?', 'To create backups of data', 'To improve performance of data retrieval queries', 'To ensure data integrity', 'To store data in secure manner', 'B', 'EASY', 'Database'],
  ['Type of relationship in relational database?', 'One-to-One', 'One-to-Many', 'Many-to-Many', 'All of the above', 'D', 'EASY', 'Database'],
  ['What does DBMS do to ensure data integrity?', 'Ensures data is always up-to-date', 'Ensures data is accurate, valid, and consistent', 'Organizes data in readable format', 'Deletes redundant data', 'B', 'EASY', 'Database'],
  ['What is a database schema?', 'Physical storage of data', 'Logical design and structure of database', 'Backup plan of database', 'A set of stored procedures', 'B', 'EASY', 'Database'],
  ['"Relationship" in relational database?', 'Connection between two pieces of data', 'Link between rows in different tables through foreign keys', 'A type of index', 'A constraint that enforces unique data', 'B', 'EASY', 'Database'],
  ['What does SELECT SQL statement do?', 'Deletes data from table', 'Inserts data into table', 'Retrieves data from table', 'Updates data in table', 'C', 'EASY', 'Database'],
  ['Purpose of a constraint in a database?', 'To ensure data retrieval is efficient', 'To define rules for data and ensure integrity', 'To allow users to access data', 'To organize data into categories', 'B', 'EASY', 'Database'],
  ['Example of many-to-many relationship?', 'Student enrolling in multiple courses with each course having multiple students', 'Customer making multiple purchases', 'Teacher teaching multiple subjects', 'Book having only one author', 'A', 'MEDIUM', 'Database'],
  ['What does JOIN operation in SQL do?', 'Combines rows from two or more tables based on related column', 'Deletes data from two tables', 'Updates data in two tables simultaneously', 'Creates new table in database', 'A', 'EASY', 'Database'],
  ['Purpose of data dictionary in DBMS?', 'To store backup data', 'To maintain information about database structure and objects', 'To store user data', 'To store encrypted passwords', 'B', 'MEDIUM', 'Database'],
  ['Main advantage of using relational database?', 'Supports unstructured data', 'Organizes data in table format ensuring consistency and integrity', 'Easier to scale than non-relational databases', 'Can store only small amounts of data', 'B', 'EASY', 'Database'],
  ['Difference between DELETE and TRUNCATE SQL statements?', 'DELETE removes all rows, TRUNCATE removes specific rows', 'DELETE is faster than TRUNCATE', 'DELETE removes specific rows, TRUNCATE removes all rows without logging', 'DELETE and TRUNCATE are identical', 'C', 'MEDIUM', 'Database'],
  ['Primary purpose of data communication?', 'To ensure data security', 'To transmit data from one device to another', 'To store data', 'To encrypt data', 'B', 'EASY', 'Networking'],
  ['Main function of OSI model in data communication?', 'To convert analog signals to digital', 'To define protocols for communication between devices', 'To store data on physical devices', 'To regulate power usage of communication devices', 'B', 'EASY', 'Networking'],
  ['OSI layer responsible for end-to-end communication?', 'Application Layer', 'Transport Layer', 'Network Layer', 'Data Link Layer', 'B', 'MEDIUM', 'Networking'],
  ['Primary function of Data Link Layer in networking?', 'Routing data across networks', 'Establishing physical connections between devices', 'Framing data packets and error detection', 'Encrypting data for secure transmission', 'C', 'MEDIUM', 'Networking'],
  ['Key difference between TCP and UDP?', 'TCP is connectionless; UDP is connection-oriented', 'TCP is slower but ensures reliability; UDP is faster but not reliable', 'TCP used only for web traffic; UDP for email', 'UDP is more secure than TCP', 'B', 'MEDIUM', 'Networking'],
  ['What does IP stand for in networking?', 'Internal Protocol', 'Internet Protocol', 'Internet Process', 'Integrated Path', 'B', 'EASY', 'Networking'],
  ['What does a router do in a computer network?', 'Connects devices within same local network', 'Provides wireless signal for devices', 'Directs data packets between different networks', 'Encrypts data sent over network', 'C', 'EASY', 'Networking'],
  ['Purpose of MAC address in networking?', 'To identify source of data packet', 'To assign IP addresses dynamically', 'To identify network interfaces at Data Link Layer', 'To secure data transmission', 'C', 'MEDIUM', 'Networking'],
  ['Example of a network topology?', 'TCP/IP', 'DNS', 'Star Topology', 'HTTP', 'C', 'EASY', 'Networking'],
  ['Common protocol for secure communication over network?', 'HTTP', 'FTP', 'HTTPS', 'POP3', 'C', 'EASY', 'Networking'],
  ['Cable most commonly used for wired Ethernet in LANs?', 'Coaxial Cable', 'Fiber Optic Cable', 'Twisted Pair Cable (Cat 5e, Cat 6)', 'USB Cable', 'C', 'EASY', 'Networking'],
  ['Maximum distance for standard Ethernet cable without signal degrading?', '50 meters', '100 meters', '200 meters', '500 meters', 'B', 'EASY', 'Networking'],
  ['Device that operates at Network Layer of OSI model?', 'Router', 'Switch', 'Hub', 'Network Interface Card', 'A', 'EASY', 'Networking'],
  ['Function of ARP (Address Resolution Protocol)?', 'Maps IP addresses to MAC addresses', 'Resolves domain names to IP addresses', 'Assigns IP addresses to devices', 'Encrypts data during transmission', 'A', 'MEDIUM', 'Networking'],
  ['Protocol responsible for assigning IP addresses to devices?', 'DNS', 'DHCP', 'FTP', 'SMTP', 'B', 'EASY', 'Networking'],
  ['Purpose of ping command in networking?', 'To test speed of network connection', 'To verify reachability of host on IP network', 'To send data packets securely', 'To retrieve IP address of device', 'B', 'EASY', 'Networking'],
  ['Primary function of firewall in computer network?', 'To route data between different networks', 'To filter and monitor incoming and outgoing traffic for security', 'To establish connection between devices', 'To encrypt data packets', 'B', 'EASY', 'Networking'],
  ['Most common IP address format used on internet?', 'IPv4', 'IPv6', 'MAC address', 'NetBIOS', 'A', 'EASY', 'Networking'],
  ['What does SSID stand for in wireless network?', 'Secure Session Identification', 'Service Set Identifier', 'Signal Strength Identification', 'System Security Identification', 'B', 'EASY', 'Networking'],
  ['Protocol used for secure file transfer over network?', 'FTP', 'SFTP', 'SMTP', 'SNMP', 'B', 'EASY', 'Networking'],
  ['What does "knowledge dissemination" refer to?', 'Process of storing knowledge', 'Process of sharing knowledge across organization or community', 'Process of creating new knowledge', 'Process of analyzing knowledge', 'B', 'EASY', 'Knowledge Management'],
  ['What does "best practices" refer to in knowledge management?', 'A type of knowledge repository', 'Proven methods or techniques that lead to optimal results', 'Knowledge shared informally among peers', 'Knowledge used exclusively for training', 'B', 'EASY', 'Knowledge Management'],
  // Knowledge Management & Scholarly Communication (51-100)
  ['Purpose of a knowledge repository?', 'To store knowledge in centralized location for easy access', 'To create new knowledge', 'To protect intellectual property', 'To evaluate employee knowledge', 'A', 'EASY', 'Knowledge Management'],
  ['Example of a knowledge management tool?', 'Microsoft Excel', 'Database management system (DBMS)', 'Enterprise Resource Planning (ERP) software', 'Document management systems (SharePoint, Confluence)', 'D', 'EASY', 'Knowledge Management'],
  ['What does "knowledge transfer" mean?', 'Process of storing knowledge in databases', 'Process of moving knowledge from one person to another to improve effectiveness', 'Process of protecting intellectual property', 'Process of creating new knowledge from existing knowledge', 'B', 'EASY', 'Knowledge Management'],
  ['Purpose of "organizational learning" in knowledge management?', 'To document all knowledge in written format', 'To facilitate continuous acquisition and application of knowledge', 'To store employee knowledge in centralized database', 'To prevent employees from sharing proprietary knowledge', 'B', 'MEDIUM', 'Knowledge Management'],
  ['Main difference between tacit and explicit knowledge?', 'Tacit knowledge is easy to share, explicit is difficult to articulate', 'Tacit is unspoken and hard to formalize, explicit can be easily codified', 'Tacit knowledge is less valuable than explicit', 'No significant difference', 'B', 'MEDIUM', 'Knowledge Management'],
  ['Strategy to capture tacit knowledge in organization?', 'Knowledge codification', 'Knowledge maps', 'Mentoring, coaching, and storytelling', 'Knowledge databases', 'C', 'MEDIUM', 'Knowledge Management'],
  ['What does "knowledge visualization" refer to?', 'Organizing data into spreadsheets', 'Using graphs, charts, and visual tools to represent knowledge', 'Creating reports based on knowledge', 'Translating knowledge into training materials', 'B', 'EASY', 'Knowledge Management'],
  ['Key challenge in managing "informal knowledge"?', 'Difficult to formalize and document for easy sharing', 'Can be easily stored in knowledge repositories', 'Can be protected by patents', 'Easily accessible to everyone', 'A', 'MEDIUM', 'Knowledge Management'],
  ['Role of leadership in knowledge management?', 'Ensures knowledge only shared among senior management', 'Fosters culture of collaboration and encourages knowledge sharing', 'Only involved in implementing technology solutions', 'Ensures knowledge is kept confidential', 'B', 'MEDIUM', 'Knowledge Management'],
  ['Common method of capturing knowledge within organization?', 'Knowledge databases', 'Knowledge surveys and feedback from employees', 'Random knowledge sharing events', 'Relying on employee memory alone', 'B', 'EASY', 'Knowledge Management'],
  ['Purpose of "content management" in knowledge management systems?', 'To design and develop new knowledge', 'To manage creation, storage, retrieval, and sharing of knowledge content', 'To analyze knowledge', 'To evaluate effectiveness of knowledge sharing', 'B', 'EASY', 'Knowledge Management'],
  ['Example of a knowledge management strategy?', 'Reducing amount of data used in decision-making', 'Encouraging employees to keep knowledge private', 'Implementing collaborative technologies to facilitate knowledge sharing', 'Limiting amount of knowledge shared within organization', 'C', 'MEDIUM', 'Knowledge Management'],
  ['"Communities of practice" (CoP) in knowledge management?', 'Method for tracking financial performance', 'Group of people sharing common interest working together to solve problems', 'Department responsible for managing knowledge', 'Process for documenting knowledge in organization', 'B', 'MEDIUM', 'Knowledge Management'],
  ['"Knowledge discovery" in knowledge management?', 'Finding hidden insights and patterns in large data sets', 'Creating new knowledge from research and development', 'Formalizing tacit knowledge', 'Securing intellectual property', 'A', 'MEDIUM', 'Knowledge Management'],
  ['Best describes an Integrated Library System (ILS)?', 'Software that only manages circulation of books', 'System that automates library functions such as cataloging, circulation, and acquisition', 'Software for managing library staff schedules', 'Database for storing book titles', 'B', 'EASY', 'Library Automation'],
  ['What does OPAC stand for in library automation?', 'Online Public Access Catalog', 'Online Private Archive Catalog', 'Online Personal Application Catalog', 'Offline Public Access Catalog', 'A', 'EASY', 'Library Automation'],
  ['Typically part of a library management system?', 'Book Circulation', 'User Registration', 'Cataloging and Indexing', 'All of the above', 'D', 'EASY', 'Library Automation'],
  ['What does RFID technology in library automation help achieve?', 'Scanning book titles into system', 'Tracking and managing library materials automatically using tags', 'Managing user access to library', 'Storing information in offline database', 'B', 'EASY', 'Library Automation'],
  ['Database model most commonly used in library automation?', 'Hierarchical Model', 'Relational Model', 'Network Model', 'Object-Oriented Model', 'B', 'EASY', 'Library Automation'],
  ['Software to track books checked out by users in automated library?', 'Circulation Software', 'Cataloging Software', 'Acquisition Software', 'Reference Management Software', 'A', 'EASY', 'Library Automation'],
  ['Features commonly included in automated library cataloging system?', 'Automated email notifications for overdue books', 'A barcode system to identify books', 'A database for book metadata', 'All of the above', 'D', 'EASY', 'Library Automation'],
  ['Role of barcode scanner in library automation systems?', 'To track user attendance', 'To retrieve data about books and users by scanning barcodes', 'To generate new book barcodes', 'To manage library finances', 'B', 'EASY', 'Library Automation'],
  ['Primary purpose of automating circulation process in library?', 'To increase accuracy and speed of book checkouts and returns', 'To generate financial reports', 'To store book reviews', 'To manage staff schedules', 'A', 'EASY', 'Library Automation'],
  ['"Acquisitions" in library automation system?', 'Process of cataloging new books', 'Process of tracking overdue books', 'Process of purchasing or acquiring new materials for library', 'Process of checking out books to users', 'C', 'EASY', 'Library Automation'],
  ['Benefit of automating library operations?', 'Reduced staffing requirements', 'Increased accessibility of library resources', 'More complicated procedures for managing books', 'Reduced reliance on technology', 'B', 'EASY', 'Library Automation'],
  ['What does "circulation desk" in library automation typically manage?', 'User registration and membership renewal', 'Book checkouts, returns, and holds', 'Cataloging and indexing of books', 'Financial transactions for library purchases', 'B', 'EASY', 'Library Automation'],
  ['What is a "self-checkout system" in library automation?', 'System where staff manually checks out books', 'System allowing library users to check out books on their own using machine', 'System used to catalog books upon arrival', 'System for ordering new books', 'B', 'EASY', 'Library Automation'],
  ['Example of tool used to digitize library materials?', 'RFID scanner', 'Barcode reader', 'Document scanner', 'Library management software', 'C', 'EASY', 'Library Automation'],
  ['Purpose of "Automated Materials Handling (AMH)" system?', 'To automate cataloging of library books', 'To track user activities within library', 'To sort and return library materials automatically', 'To provide Wi-Fi access in library', 'C', 'EASY', 'Library Automation'],
  ['"Reserve management" in library automation system?', 'Tracking overdue books', 'Managing user requests for books that are checked out', 'Generating library reports', 'Monitoring user activity', 'B', 'EASY', 'Library Automation'],
  ['Primary purpose of scholarly communication?', 'To share personal opinions with public', 'To disseminate research findings to academic community and general public', 'To discuss entertainment topics', 'To store academic papers for future use', 'B', 'EASY', 'Scholarly Communication'],
  ['NOT a typical medium for scholarly communication?', 'Peer-reviewed journals', 'Blogs and social media posts', 'Conference presentations', 'Books', 'B', 'EASY', 'Scholarly Communication'],
  ['What is peer review in scholarly communication?', 'Process where researchers critique each other\'s work before publishing', 'Form of advertisement for research papers', 'Process of selling academic articles to publishers', 'Method of promoting research findings on social media', 'A', 'EASY', 'Scholarly Communication'],
  ['Example of an open-access journal?', 'Nature', 'Journal of Scholarly Publishing', 'Public Library of Science (PLoS)', 'IEEE Transactions on Computers', 'C', 'EASY', 'Scholarly Communication'],
  ['Role of a scholarly journal?', 'To entertain audience with research findings', 'To publish research articles contributing to academic body of knowledge', 'To advertise new products in research', 'To share personal opinions on societal issues', 'B', 'EASY', 'Scholarly Communication'],
  ['What does "impact factor" refer to in scholarly communication?', 'Amount of funding journal receives', 'Speed at which research paper is published', 'Measure of journal\'s influence based on citations', 'Number of pages in article', 'C', 'MEDIUM', 'Scholarly Communication'],
  ['What is a "citation" in scholarly communication?', 'Way to give credit to author for their work', 'Reference to research paper in unrelated field', 'Type of document published in journals', 'Form of advertisement for books', 'A', 'EASY', 'Scholarly Communication'],
  ['What is "scholarly publishing"?', 'Publishing commercial books', 'Publishing research and academic works to advance knowledge', 'Publishing content for public entertainment', 'Writing blogs and online articles', 'B', 'EASY', 'Scholarly Communication'],
  ['Characteristic of an academic conference?', 'Primarily for discussing news and entertainment', 'Event where researchers present and discuss scholarly work', 'Platform for publishing books', 'Networking event for job seekers', 'B', 'EASY', 'Scholarly Communication'],
  ['What is "open-access publishing"?', 'Method where only select users can access published papers', 'Publishing model where research is freely available without subscription', 'Process where authors must pay to have work published', 'Publishing model focusing on humanities research', 'B', 'EASY', 'Scholarly Communication'],
  ['Potential issue with traditional scholarly publishing model?', 'Rapid spread of research findings', 'High cost of accessing academic journals', 'Ease of peer review', 'Low-quality standards for publications', 'B', 'MEDIUM', 'Scholarly Communication'],
  ['Function of DOI (digital object identifier)?', 'Helps determine financial value of research paper', 'Provides unique and permanent link to digital article', 'Evaluates quality of academic work', 'Manages citation process', 'B', 'EASY', 'Scholarly Communication'],
  ['What describes a scholarly article\'s "abstract"?', 'Brief summary of article\'s contents including research problem, methodology, and results', 'Detailed explanation of methodology used', 'List of references cited in article', 'Personal opinion about research topic', 'A', 'EASY', 'Scholarly Communication'],
  ['What does "plagiarism" mean in scholarly communication?', 'Citing another author\'s work properly', 'Using another author\'s work without proper attribution or permission', 'Writing a research paper', 'Providing full access to research papers', 'B', 'EASY', 'Scholarly Communication'],
  ['Importance of citations in scholarly communication?', 'Help in advertising new research findings', 'Allow readers to verify sources and build upon existing knowledge', 'Used to summarize research findings', 'Only used to fill space in academic articles', 'B', 'EASY', 'Scholarly Communication'],
  ['"Primary source" in scholarly communication?', 'Review article summarizing previous research', 'Book discussing several research findings', 'Original research paper presenting new experimental results', 'News article discussing scientific topics', 'C', 'EASY', 'Scholarly Communication'],
  ['What is "ResearchGate"?', 'Place for finding commercial articles', 'Platform where researchers share papers, ask questions, and connect with others', 'A scholarly publishing journal', 'Tool for editing research papers', 'B', 'EASY', 'Scholarly Communication'],
  ['What is a "bibliography" in scholarly writing?', 'Summary of research paper', 'List of sources referenced in scholarly work', 'Tool for searching academic journals', 'Discussion of research findings', 'B', 'EASY', 'Scholarly Communication'],
  ['What does "reproducibility" mean in scholarly research?', 'Ability to repeat study and obtain similar results', 'Ability to summarize research findings', 'Ability to store research findings online', 'Ability to present findings at conference', 'A', 'MEDIUM', 'Scholarly Communication'],
  ['Example of secondary source in scholarly communication?', 'Journal article presenting original research', 'Thesis based on original research', 'Review article summarizing multiple studies on topic', 'Dataset collected for study', 'C', 'EASY', 'Scholarly Communication'],
  ['What does "altmetrics" stand for?', 'Academic metric based on traditional citation counts', 'Alternative metrics measuring online engagement and impact of research', 'System for ranking academic journals', 'Collection of metrics for funding research grants', 'B', 'MEDIUM', 'Scholarly Communication'],
]

// ─── Seed Function ───────────────────────────────────────────────────────────

async function seed() {
  await connectDB()

  // Clear existing data
  await Promise.all([
    User.deleteMany({}),
    Subject.deleteMany({}),
    Question.deleteMany({}),
    Exam.deleteMany({}),
  ])
  console.log('Cleared existing data')

  // Create users
  const adminPass = await bcrypt.hash('admin123', 10)
  const studentPass = await bcrypt.hash('student123', 10)
  await User.create([
    { name: 'Admin', email: 'admin@example.com', password: adminPass, role: 'admin' },
    { name: 'Student', email: 'student@example.com', password: studentPass, role: 'student' },
  ])
  console.log('Created users')

  // Create subject
  const subject = await Subject.create({
    name: 'Information Science',
    code: 'IS',
    description: 'BSc Information Science Exit Exam',
  })
  console.log('Created subject')

  // Helper to create questions and exam
  async function createModelExam(
    modelNum: number,
    qs: Q[],
    description: string
  ) {
    const questionDocs = await Question.insertMany(
      qs.map(([question, optionA, optionB, optionC, optionD, correctAnswer, difficulty, topic]) => ({
        question, optionA, optionB, optionC, optionD,
        correctAnswer, difficulty, topic,
        subject: subject._id, type: 'MCQ',
      }))
    )
    const exam = await Exam.create({
      title: `BSc Information Science — Model Exam ${modelNum}`,
      subject: subject._id,
      questions: questionDocs.map((q: any) => q._id),
      timeLimit: 120,
      passingMark: 50,
      type: 'MOCK',
      isActive: true,
      description,
    })
    console.log(`Created Model Exam ${modelNum} with ${questionDocs.length} questions (ID: ${exam._id})`)
    return exam
  }

  await createModelExam(1, MODEL1_QS, 'Data Structures, Algorithms & Information Science Fundamentals')
  await createModelExam(2, MODEL2_QS, 'Library Science, Digital Libraries & Information Retrieval')
  await createModelExam(3, MODEL3_QS, 'Programming, Visual Basic & Web Development')
  await createModelExam(4, MODEL4_QS, 'Database Systems, Networking, Knowledge Management & Scholarly Communication')

  console.log('\n✅ Seed complete!')
  console.log('Admin:   admin@example.com / admin123')
  console.log('Student: student@example.com / student123')
  await mongoose.disconnect()
}

seed().catch(err => { console.error(err); process.exit(1) })
